Quick sort in JAVA added.
shashwatj07/scripts pull request #6
Opened 2021-10-07 10:25 UTC by SamikshyaMstar

I have added Quicksort in JAVA.

2021-10-07 17:05 UTC, anantcodes requested changes

2021-10-07 17:05 UTC, anantcodes commented on QuickSorting.java
> +        quick(a, 0, n - 1);
Mention the space and time complexity of the approach used.

2021-10-07 17:05 UTC, anantcodes commented on QuickSorting.java
> +        for (int i = 0; i < n; i++){
Give proper indentation throughout.

2021-10-07 17:05 UTC, anantcodes commented on QuickSorting.java
> +
Remove extraneous newlines.

2021-10-08 14:38 UTC, SamikshyaMstar commented on QuickSorting.java
> +
ok

2021-10-08 14:38 UTC, SamikshyaMstar commented on QuickSorting.java
> +        for (int i = 0; i < n; i++){
ok

2021-10-08 14:38 UTC, SamikshyaMstar commented on QuickSorting.java
> +        quick(a, 0, n - 1);
ok

2021-10-08 15:01 UTC, SamikshyaMstar commented
I have modified my PR. Please review the same @anantcodes.

2021-10-08 15:03 UTC, SamikshyaMstar commented
@shashwatj07 kindly merge my PR.

2021-10-08 16:22 UTC, anantcodes approved these changes
Lgtm

2021-10-09 15:34 UTC, shashwatj07 approved these changes

2021-10-09 15:35 UTC, merged